// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "heatwave3_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// label_components_cpp
IntegerVector label_components_cpp(IntegerVector mask, int nx, int ny, int nz, int nt, bool wrap_dateline);
RcppExport SEXP _heatwave3_label_components_cpp(SEXP maskSEXP, SEXP nxSEXP, SEXP nySEXP, SEXP nzSEXP, SEXP ntSEXP, SEXP wrap_datelineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< int >::type ny(nySEXP);
    Rcpp::traits::input_parameter< int >::type nz(nzSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< bool >::type wrap_dateline(wrap_datelineSEXP);
    rcpp_result_gen = Rcpp::wrap(label_components_cpp(mask, nx, ny, nz, nt, wrap_dateline));
    return rcpp_result_gen;
END_RCPP
}
// blob_daily_summary_cpp
List blob_daily_summary_cpp(IntegerVector labels, IntegerVector ix, IntegerVector iy, IntegerVector it, NumericVector delta, NumericVector cell_area_lat, NumericVector lons, NumericVector lats, int nt, IntegerVector iz, NumericVector depths, NumericVector layer_thickness_km, bool has_depth);
RcppExport SEXP _heatwave3_blob_daily_summary_cpp(SEXP labelsSEXP, SEXP ixSEXP, SEXP iySEXP, SEXP itSEXP, SEXP deltaSEXP, SEXP cell_area_latSEXP, SEXP lonsSEXP, SEXP latsSEXP, SEXP ntSEXP, SEXP izSEXP, SEXP depthsSEXP, SEXP layer_thickness_kmSEXP, SEXP has_depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ix(ixSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type iy(iySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type it(itSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cell_area_lat(cell_area_latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lons(lonsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type iz(izSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type depths(depthsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type layer_thickness_km(layer_thickness_kmSEXP);
    Rcpp::traits::input_parameter< bool >::type has_depth(has_depthSEXP);
    rcpp_result_gen = Rcpp::wrap(blob_daily_summary_cpp(labels, ix, iy, it, delta, cell_area_lat, lons, lats, nt, iz, depths, layer_thickness_km, has_depth));
    return rcpp_result_gen;
END_RCPP
}
// hw3_get_threads
int hw3_get_threads();
RcppExport SEXP _heatwave3_hw3_get_threads() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(hw3_get_threads());
    return rcpp_result_gen;
END_RCPP
}
// hw3_set_threads
int hw3_set_threads(int n);
RcppExport SEXP _heatwave3_hw3_set_threads(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_set_threads(n));
    return rcpp_result_gen;
END_RCPP
}
// hw3_init_fork_safety
void hw3_init_fork_safety();
RcppExport SEXP _heatwave3_hw3_init_fork_safety() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    hw3_init_fork_safety();
    return R_NilValue;
END_RCPP
}
// hw3_version
Rcpp::List hw3_version();
RcppExport SEXP _heatwave3_hw3_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(hw3_version());
    return rcpp_result_gen;
END_RCPP
}
// hw3_read_sst
Rcpp::List hw3_read_sst(std::string file_in, std::string var_name, Rcpp::Nullable<Rcpp::NumericVector> lon_range, Rcpp::Nullable<Rcpp::NumericVector> lat_range, Rcpp::Nullable<Rcpp::CharacterVector> time_range, int depth, Rcpp::Nullable<Rcpp::NumericVector> depth_range);
RcppExport SEXP _heatwave3_hw3_read_sst(SEXP file_inSEXP, SEXP var_nameSEXP, SEXP lon_rangeSEXP, SEXP lat_rangeSEXP, SEXP time_rangeSEXP, SEXP depthSEXP, SEXP depth_rangeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_in(file_inSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lon_range(lon_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lat_range(lat_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type time_range(time_rangeSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type depth_range(depth_rangeSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_read_sst(file_in, var_name, lon_range, lat_range, time_range, depth, depth_range));
    return rcpp_result_gen;
END_RCPP
}
// hw3_read_sst_multi
Rcpp::List hw3_read_sst_multi(Rcpp::CharacterVector files, std::string var_name, Rcpp::Nullable<Rcpp::NumericVector> lon_range, Rcpp::Nullable<Rcpp::NumericVector> lat_range, int depth, bool skip_bad_files, Rcpp::Nullable<Rcpp::NumericVector> depth_range);
RcppExport SEXP _heatwave3_hw3_read_sst_multi(SEXP filesSEXP, SEXP var_nameSEXP, SEXP lon_rangeSEXP, SEXP lat_rangeSEXP, SEXP depthSEXP, SEXP skip_bad_filesSEXP, SEXP depth_rangeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lon_range(lon_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lat_range(lat_rangeSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_bad_files(skip_bad_filesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type depth_range(depth_rangeSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_read_sst_multi(files, var_name, lon_range, lat_range, depth, skip_bad_files, depth_range));
    return rcpp_result_gen;
END_RCPP
}
// hw3_pixel_clim
Rcpp::List hw3_pixel_clim(Rcpp::NumericVector temp, Rcpp::IntegerVector time_jd, std::string clim_start, std::string clim_end, int windowHalfWidth, double pctile, bool smoothPercentile, int smoothPercentileWidth, int maxPadLength, bool detrend);
RcppExport SEXP _heatwave3_hw3_pixel_clim(SEXP tempSEXP, SEXP time_jdSEXP, SEXP clim_startSEXP, SEXP clim_endSEXP, SEXP windowHalfWidthSEXP, SEXP pctileSEXP, SEXP smoothPercentileSEXP, SEXP smoothPercentileWidthSEXP, SEXP maxPadLengthSEXP, SEXP detrendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type time_jd(time_jdSEXP);
    Rcpp::traits::input_parameter< std::string >::type clim_start(clim_startSEXP);
    Rcpp::traits::input_parameter< std::string >::type clim_end(clim_endSEXP);
    Rcpp::traits::input_parameter< int >::type windowHalfWidth(windowHalfWidthSEXP);
    Rcpp::traits::input_parameter< double >::type pctile(pctileSEXP);
    Rcpp::traits::input_parameter< bool >::type smoothPercentile(smoothPercentileSEXP);
    Rcpp::traits::input_parameter< int >::type smoothPercentileWidth(smoothPercentileWidthSEXP);
    Rcpp::traits::input_parameter< int >::type maxPadLength(maxPadLengthSEXP);
    Rcpp::traits::input_parameter< bool >::type detrend(detrendSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_pixel_clim(temp, time_jd, clim_start, clim_end, windowHalfWidth, pctile, smoothPercentile, smoothPercentileWidth, maxPadLength, detrend));
    return rcpp_result_gen;
END_RCPP
}
// hw3_compute_clim
void hw3_compute_clim(std::string file_in, std::string file_out, std::string var_name, Rcpp::CharacterVector climatologyPeriod, Rcpp::Nullable<Rcpp::NumericVector> lon_range, Rcpp::Nullable<Rcpp::NumericVector> lat_range, Rcpp::Nullable<Rcpp::CharacterVector> time_range, int depth, int maxPadLength, int windowHalfWidth, double pctile, bool smoothPercentile, int smoothPercentileWidth, bool compute_var, int roundClm, int n_threads, bool detrend, Rcpp::Nullable<Rcpp::NumericVector> depth_range);
RcppExport SEXP _heatwave3_hw3_compute_clim(SEXP file_inSEXP, SEXP file_outSEXP, SEXP var_nameSEXP, SEXP climatologyPeriodSEXP, SEXP lon_rangeSEXP, SEXP lat_rangeSEXP, SEXP time_rangeSEXP, SEXP depthSEXP, SEXP maxPadLengthSEXP, SEXP windowHalfWidthSEXP, SEXP pctileSEXP, SEXP smoothPercentileSEXP, SEXP smoothPercentileWidthSEXP, SEXP compute_varSEXP, SEXP roundClmSEXP, SEXP n_threadsSEXP, SEXP detrendSEXP, SEXP depth_rangeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_in(file_inSEXP);
    Rcpp::traits::input_parameter< std::string >::type file_out(file_outSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type climatologyPeriod(climatologyPeriodSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lon_range(lon_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lat_range(lat_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type time_range(time_rangeSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type maxPadLength(maxPadLengthSEXP);
    Rcpp::traits::input_parameter< int >::type windowHalfWidth(windowHalfWidthSEXP);
    Rcpp::traits::input_parameter< double >::type pctile(pctileSEXP);
    Rcpp::traits::input_parameter< bool >::type smoothPercentile(smoothPercentileSEXP);
    Rcpp::traits::input_parameter< int >::type smoothPercentileWidth(smoothPercentileWidthSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_var(compute_varSEXP);
    Rcpp::traits::input_parameter< int >::type roundClm(roundClmSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type detrend(detrendSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type depth_range(depth_rangeSEXP);
    hw3_compute_clim(file_in, file_out, var_name, climatologyPeriod, lon_range, lat_range, time_range, depth, maxPadLength, windowHalfWidth, pctile, smoothPercentile, smoothPercentileWidth, compute_var, roundClm, n_threads, detrend, depth_range);
    return R_NilValue;
END_RCPP
}
// hw3_compute_clim_multi
void hw3_compute_clim_multi(Rcpp::CharacterVector files, std::string file_out, std::string var_name, Rcpp::CharacterVector climatologyPeriod, Rcpp::Nullable<Rcpp::NumericVector> lon_range, Rcpp::Nullable<Rcpp::NumericVector> lat_range, int depth, int maxPadLength, int windowHalfWidth, double pctile, bool smoothPercentile, int smoothPercentileWidth, bool compute_var, int roundClm, int n_threads, bool detrend, bool skip_bad_files, Rcpp::Nullable<Rcpp::NumericVector> depth_range);
RcppExport SEXP _heatwave3_hw3_compute_clim_multi(SEXP filesSEXP, SEXP file_outSEXP, SEXP var_nameSEXP, SEXP climatologyPeriodSEXP, SEXP lon_rangeSEXP, SEXP lat_rangeSEXP, SEXP depthSEXP, SEXP maxPadLengthSEXP, SEXP windowHalfWidthSEXP, SEXP pctileSEXP, SEXP smoothPercentileSEXP, SEXP smoothPercentileWidthSEXP, SEXP compute_varSEXP, SEXP roundClmSEXP, SEXP n_threadsSEXP, SEXP detrendSEXP, SEXP skip_bad_filesSEXP, SEXP depth_rangeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< std::string >::type file_out(file_outSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type climatologyPeriod(climatologyPeriodSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lon_range(lon_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lat_range(lat_rangeSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type maxPadLength(maxPadLengthSEXP);
    Rcpp::traits::input_parameter< int >::type windowHalfWidth(windowHalfWidthSEXP);
    Rcpp::traits::input_parameter< double >::type pctile(pctileSEXP);
    Rcpp::traits::input_parameter< bool >::type smoothPercentile(smoothPercentileSEXP);
    Rcpp::traits::input_parameter< int >::type smoothPercentileWidth(smoothPercentileWidthSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_var(compute_varSEXP);
    Rcpp::traits::input_parameter< int >::type roundClm(roundClmSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type detrend(detrendSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_bad_files(skip_bad_filesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type depth_range(depth_rangeSEXP);
    hw3_compute_clim_multi(files, file_out, var_name, climatologyPeriod, lon_range, lat_range, depth, maxPadLength, windowHalfWidth, pctile, smoothPercentile, smoothPercentileWidth, compute_var, roundClm, n_threads, detrend, skip_bad_files, depth_range);
    return R_NilValue;
END_RCPP
}
// hw3_write_const_clim
void hw3_write_const_clim(std::string file_in, std::string clim_file, std::string var_name, double threshold, Rcpp::Nullable<Rcpp::NumericVector> lon_range, Rcpp::Nullable<Rcpp::NumericVector> lat_range, Rcpp::Nullable<Rcpp::CharacterVector> time_range, int depth);
RcppExport SEXP _heatwave3_hw3_write_const_clim(SEXP file_inSEXP, SEXP clim_fileSEXP, SEXP var_nameSEXP, SEXP thresholdSEXP, SEXP lon_rangeSEXP, SEXP lat_rangeSEXP, SEXP time_rangeSEXP, SEXP depthSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_in(file_inSEXP);
    Rcpp::traits::input_parameter< std::string >::type clim_file(clim_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lon_range(lon_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lat_range(lat_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type time_range(time_rangeSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    hw3_write_const_clim(file_in, clim_file, var_name, threshold, lon_range, lat_range, time_range, depth);
    return R_NilValue;
END_RCPP
}
// hw3_jd_to_doy
int hw3_jd_to_doy(int jd);
RcppExport SEXP _heatwave3_hw3_jd_to_doy(SEXP jdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type jd(jdSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_jd_to_doy(jd));
    return rcpp_result_gen;
END_RCPP
}
// hw3_read_clim_nc
Rcpp::List hw3_read_clim_nc(std::string clim_file);
RcppExport SEXP _heatwave3_hw3_read_clim_nc(SEXP clim_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type clim_file(clim_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_read_clim_nc(clim_file));
    return rcpp_result_gen;
END_RCPP
}
// hw3_read_subset
Rcpp::List hw3_read_subset(std::string file, Rcpp::Nullable<Rcpp::NumericVector> lon_range, Rcpp::Nullable<Rcpp::NumericVector> lat_range, Rcpp::Nullable<Rcpp::IntegerVector> t_jd_range, Rcpp::Nullable<Rcpp::NumericVector> depth_range, Rcpp::Nullable<Rcpp::CharacterVector> vars, int max_rows);
RcppExport SEXP _heatwave3_hw3_read_subset(SEXP fileSEXP, SEXP lon_rangeSEXP, SEXP lat_rangeSEXP, SEXP t_jd_rangeSEXP, SEXP depth_rangeSEXP, SEXP varsSEXP, SEXP max_rowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lon_range(lon_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lat_range(lat_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type t_jd_range(t_jd_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type depth_range(depth_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< int >::type max_rows(max_rowsSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_read_subset(file, lon_range, lat_range, t_jd_range, depth_range, vars, max_rows));
    return rcpp_result_gen;
END_RCPP
}
// hw3_category_daily
Rcpp::List hw3_category_daily(std::string sst_file, std::string clim_file, std::string event_file, std::vector<int> t_jd_range, std::string var_name, bool coldSpells, double ice_thresh, int roundRes);
RcppExport SEXP _heatwave3_hw3_category_daily(SEXP sst_fileSEXP, SEXP clim_fileSEXP, SEXP event_fileSEXP, SEXP t_jd_rangeSEXP, SEXP var_nameSEXP, SEXP coldSpellsSEXP, SEXP ice_threshSEXP, SEXP roundResSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type sst_file(sst_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type clim_file(clim_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type event_file(event_fileSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type t_jd_range(t_jd_rangeSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type coldSpells(coldSpellsSEXP);
    Rcpp::traits::input_parameter< double >::type ice_thresh(ice_threshSEXP);
    Rcpp::traits::input_parameter< int >::type roundRes(roundResSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_category_daily(sst_file, clim_file, event_file, t_jd_range, var_name, coldSpells, ice_thresh, roundRes));
    return rcpp_result_gen;
END_RCPP
}
// hw3_category_daily_multi
Rcpp::List hw3_category_daily_multi(Rcpp::CharacterVector files, std::string clim_file, std::string event_file, std::vector<int> t_jd_range, std::string var_name, bool coldSpells, double ice_thresh, int roundRes, bool skip_bad_files);
RcppExport SEXP _heatwave3_hw3_category_daily_multi(SEXP filesSEXP, SEXP clim_fileSEXP, SEXP event_fileSEXP, SEXP t_jd_rangeSEXP, SEXP var_nameSEXP, SEXP coldSpellsSEXP, SEXP ice_threshSEXP, SEXP roundResSEXP, SEXP skip_bad_filesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< std::string >::type clim_file(clim_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type event_file(event_fileSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type t_jd_range(t_jd_rangeSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type coldSpells(coldSpellsSEXP);
    Rcpp::traits::input_parameter< double >::type ice_thresh(ice_threshSEXP);
    Rcpp::traits::input_parameter< int >::type roundRes(roundResSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_bad_files(skip_bad_filesSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_category_daily_multi(files, clim_file, event_file, t_jd_range, var_name, coldSpells, ice_thresh, roundRes, skip_bad_files));
    return rcpp_result_gen;
END_RCPP
}
// hw3_file_meta
Rcpp::List hw3_file_meta(std::string file);
RcppExport SEXP _heatwave3_hw3_file_meta(SEXP fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_file_meta(file));
    return rcpp_result_gen;
END_RCPP
}
// hw3_read_daily_nc
Rcpp::List hw3_read_daily_nc(std::string daily_file);
RcppExport SEXP _heatwave3_hw3_read_daily_nc(SEXP daily_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type daily_file(daily_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_read_daily_nc(daily_file));
    return rcpp_result_gen;
END_RCPP
}
// hw3_detect_events
void hw3_detect_events(std::string file_in, std::string clim_file, std::string events_file, std::string var_name, int minDuration, int minDuration2, bool joinAcrossGaps, int maxGap, int maxGap2, bool coldSpells, int roundRes, int n_threads, bool category, bool southHemisphere, std::string threshClim2_file, std::string threshClim2_var_name, std::string daily_file, std::string proto_file);
RcppExport SEXP _heatwave3_hw3_detect_events(SEXP file_inSEXP, SEXP clim_fileSEXP, SEXP events_fileSEXP, SEXP var_nameSEXP, SEXP minDurationSEXP, SEXP minDuration2SEXP, SEXP joinAcrossGapsSEXP, SEXP maxGapSEXP, SEXP maxGap2SEXP, SEXP coldSpellsSEXP, SEXP roundResSEXP, SEXP n_threadsSEXP, SEXP categorySEXP, SEXP southHemisphereSEXP, SEXP threshClim2_fileSEXP, SEXP threshClim2_var_nameSEXP, SEXP daily_fileSEXP, SEXP proto_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_in(file_inSEXP);
    Rcpp::traits::input_parameter< std::string >::type clim_file(clim_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type events_file(events_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< int >::type minDuration(minDurationSEXP);
    Rcpp::traits::input_parameter< int >::type minDuration2(minDuration2SEXP);
    Rcpp::traits::input_parameter< bool >::type joinAcrossGaps(joinAcrossGapsSEXP);
    Rcpp::traits::input_parameter< int >::type maxGap(maxGapSEXP);
    Rcpp::traits::input_parameter< int >::type maxGap2(maxGap2SEXP);
    Rcpp::traits::input_parameter< bool >::type coldSpells(coldSpellsSEXP);
    Rcpp::traits::input_parameter< int >::type roundRes(roundResSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type category(categorySEXP);
    Rcpp::traits::input_parameter< bool >::type southHemisphere(southHemisphereSEXP);
    Rcpp::traits::input_parameter< std::string >::type threshClim2_file(threshClim2_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type threshClim2_var_name(threshClim2_var_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type daily_file(daily_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type proto_file(proto_fileSEXP);
    hw3_detect_events(file_in, clim_file, events_file, var_name, minDuration, minDuration2, joinAcrossGaps, maxGap, maxGap2, coldSpells, roundRes, n_threads, category, southHemisphere, threshClim2_file, threshClim2_var_name, daily_file, proto_file);
    return R_NilValue;
END_RCPP
}
// hw3_detect_events_multi
void hw3_detect_events_multi(Rcpp::CharacterVector files, std::string clim_file, std::string events_file, std::string var_name, int minDuration, int minDuration2, bool joinAcrossGaps, int maxGap, int maxGap2, bool coldSpells, int roundRes, int n_threads, bool category, bool southHemisphere, Rcpp::Nullable<Rcpp::CharacterVector> threshClim2_files, std::string threshClim2_var_name, bool skip_bad_files, std::string daily_file, std::string proto_file);
RcppExport SEXP _heatwave3_hw3_detect_events_multi(SEXP filesSEXP, SEXP clim_fileSEXP, SEXP events_fileSEXP, SEXP var_nameSEXP, SEXP minDurationSEXP, SEXP minDuration2SEXP, SEXP joinAcrossGapsSEXP, SEXP maxGapSEXP, SEXP maxGap2SEXP, SEXP coldSpellsSEXP, SEXP roundResSEXP, SEXP n_threadsSEXP, SEXP categorySEXP, SEXP southHemisphereSEXP, SEXP threshClim2_filesSEXP, SEXP threshClim2_var_nameSEXP, SEXP skip_bad_filesSEXP, SEXP daily_fileSEXP, SEXP proto_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< std::string >::type clim_file(clim_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type events_file(events_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< int >::type minDuration(minDurationSEXP);
    Rcpp::traits::input_parameter< int >::type minDuration2(minDuration2SEXP);
    Rcpp::traits::input_parameter< bool >::type joinAcrossGaps(joinAcrossGapsSEXP);
    Rcpp::traits::input_parameter< int >::type maxGap(maxGapSEXP);
    Rcpp::traits::input_parameter< int >::type maxGap2(maxGap2SEXP);
    Rcpp::traits::input_parameter< bool >::type coldSpells(coldSpellsSEXP);
    Rcpp::traits::input_parameter< int >::type roundRes(roundResSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type category(categorySEXP);
    Rcpp::traits::input_parameter< bool >::type southHemisphere(southHemisphereSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type threshClim2_files(threshClim2_filesSEXP);
    Rcpp::traits::input_parameter< std::string >::type threshClim2_var_name(threshClim2_var_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_bad_files(skip_bad_filesSEXP);
    Rcpp::traits::input_parameter< std::string >::type daily_file(daily_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type proto_file(proto_fileSEXP);
    hw3_detect_events_multi(files, clim_file, events_file, var_name, minDuration, minDuration2, joinAcrossGaps, maxGap, maxGap2, coldSpells, roundRes, n_threads, category, southHemisphere, threshClim2_files, threshClim2_var_name, skip_bad_files, daily_file, proto_file);
    return R_NilValue;
END_RCPP
}
// hw3_read_event_nc
Rcpp::List hw3_read_event_nc(std::string event_file);
RcppExport SEXP _heatwave3_hw3_read_event_nc(SEXP event_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type event_file(event_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_read_event_nc(event_file));
    return rcpp_result_gen;
END_RCPP
}
// hw3_category
Rcpp::DataFrame hw3_category(std::string event_file, std::string clim_file, std::string hemisphere, int roundVal);
RcppExport SEXP _heatwave3_hw3_category(SEXP event_fileSEXP, SEXP clim_fileSEXP, SEXP hemisphereSEXP, SEXP roundValSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type event_file(event_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type clim_file(clim_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type hemisphere(hemisphereSEXP);
    Rcpp::traits::input_parameter< int >::type roundVal(roundValSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_category(event_file, clim_file, hemisphere, roundVal));
    return rcpp_result_gen;
END_RCPP
}
// hw3_block_average
Rcpp::DataFrame hw3_block_average(std::string event_file);
RcppExport SEXP _heatwave3_hw3_block_average(SEXP event_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type event_file(event_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_block_average(event_file));
    return rcpp_result_gen;
END_RCPP
}
// hw3_read_metric_summary
Rcpp::DataFrame hw3_read_metric_summary(std::string event_file, std::string metric, std::string summary);
RcppExport SEXP _heatwave3_hw3_read_metric_summary(SEXP event_fileSEXP, SEXP metricSEXP, SEXP summarySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type event_file(event_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< std::string >::type summary(summarySEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_read_metric_summary(event_file, metric, summary));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_heatwave3_label_components_cpp", (DL_FUNC) &_heatwave3_label_components_cpp, 6},
    {"_heatwave3_blob_daily_summary_cpp", (DL_FUNC) &_heatwave3_blob_daily_summary_cpp, 13},
    {"_heatwave3_hw3_get_threads", (DL_FUNC) &_heatwave3_hw3_get_threads, 0},
    {"_heatwave3_hw3_set_threads", (DL_FUNC) &_heatwave3_hw3_set_threads, 1},
    {"_heatwave3_hw3_init_fork_safety", (DL_FUNC) &_heatwave3_hw3_init_fork_safety, 0},
    {"_heatwave3_hw3_version", (DL_FUNC) &_heatwave3_hw3_version, 0},
    {"_heatwave3_hw3_read_sst", (DL_FUNC) &_heatwave3_hw3_read_sst, 7},
    {"_heatwave3_hw3_read_sst_multi", (DL_FUNC) &_heatwave3_hw3_read_sst_multi, 7},
    {"_heatwave3_hw3_pixel_clim", (DL_FUNC) &_heatwave3_hw3_pixel_clim, 10},
    {"_heatwave3_hw3_compute_clim", (DL_FUNC) &_heatwave3_hw3_compute_clim, 18},
    {"_heatwave3_hw3_compute_clim_multi", (DL_FUNC) &_heatwave3_hw3_compute_clim_multi, 18},
    {"_heatwave3_hw3_write_const_clim", (DL_FUNC) &_heatwave3_hw3_write_const_clim, 8},
    {"_heatwave3_hw3_jd_to_doy", (DL_FUNC) &_heatwave3_hw3_jd_to_doy, 1},
    {"_heatwave3_hw3_read_clim_nc", (DL_FUNC) &_heatwave3_hw3_read_clim_nc, 1},
    {"_heatwave3_hw3_read_subset", (DL_FUNC) &_heatwave3_hw3_read_subset, 7},
    {"_heatwave3_hw3_category_daily", (DL_FUNC) &_heatwave3_hw3_category_daily, 8},
    {"_heatwave3_hw3_category_daily_multi", (DL_FUNC) &_heatwave3_hw3_category_daily_multi, 9},
    {"_heatwave3_hw3_file_meta", (DL_FUNC) &_heatwave3_hw3_file_meta, 1},
    {"_heatwave3_hw3_read_daily_nc", (DL_FUNC) &_heatwave3_hw3_read_daily_nc, 1},
    {"_heatwave3_hw3_detect_events", (DL_FUNC) &_heatwave3_hw3_detect_events, 18},
    {"_heatwave3_hw3_detect_events_multi", (DL_FUNC) &_heatwave3_hw3_detect_events_multi, 19},
    {"_heatwave3_hw3_read_event_nc", (DL_FUNC) &_heatwave3_hw3_read_event_nc, 1},
    {"_heatwave3_hw3_category", (DL_FUNC) &_heatwave3_hw3_category, 4},
    {"_heatwave3_hw3_block_average", (DL_FUNC) &_heatwave3_hw3_block_average, 1},
    {"_heatwave3_hw3_read_metric_summary", (DL_FUNC) &_heatwave3_hw3_read_metric_summary, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_heatwave3(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
