// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "heatwave3_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// label_components_3d_cpp
IntegerVector label_components_3d_cpp(IntegerVector mask, int nx, int ny, int nt, bool wrap_dateline);
RcppExport SEXP _heatwave3_label_components_3d_cpp(SEXP maskSEXP, SEXP nxSEXP, SEXP nySEXP, SEXP ntSEXP, SEXP wrap_datelineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< int >::type ny(nySEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< bool >::type wrap_dateline(wrap_datelineSEXP);
    rcpp_result_gen = Rcpp::wrap(label_components_3d_cpp(mask, nx, ny, nt, wrap_dateline));
    return rcpp_result_gen;
END_RCPP
}
// blob_daily_summary_cpp
List blob_daily_summary_cpp(IntegerVector labels, IntegerVector ix, IntegerVector iy, IntegerVector it, NumericVector delta, NumericVector cell_area_lat, NumericVector lons, NumericVector lats, int nt);
RcppExport SEXP _heatwave3_blob_daily_summary_cpp(SEXP labelsSEXP, SEXP ixSEXP, SEXP iySEXP, SEXP itSEXP, SEXP deltaSEXP, SEXP cell_area_latSEXP, SEXP lonsSEXP, SEXP latsSEXP, SEXP ntSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ix(ixSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type iy(iySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type it(itSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cell_area_lat(cell_area_latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lons(lonsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    rcpp_result_gen = Rcpp::wrap(blob_daily_summary_cpp(labels, ix, iy, it, delta, cell_area_lat, lons, lats, nt));
    return rcpp_result_gen;
END_RCPP
}
// hw3_version
Rcpp::List hw3_version();
RcppExport SEXP _heatwave3_hw3_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(hw3_version());
    return rcpp_result_gen;
END_RCPP
}
// hw3_read_sst
Rcpp::List hw3_read_sst(std::string file_in, std::string var_name, Rcpp::Nullable<Rcpp::NumericVector> lon_range, Rcpp::Nullable<Rcpp::NumericVector> lat_range, Rcpp::Nullable<Rcpp::CharacterVector> time_range, int depth);
RcppExport SEXP _heatwave3_hw3_read_sst(SEXP file_inSEXP, SEXP var_nameSEXP, SEXP lon_rangeSEXP, SEXP lat_rangeSEXP, SEXP time_rangeSEXP, SEXP depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_in(file_inSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lon_range(lon_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lat_range(lat_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type time_range(time_rangeSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_read_sst(file_in, var_name, lon_range, lat_range, time_range, depth));
    return rcpp_result_gen;
END_RCPP
}
// hw3_read_sst_multi
Rcpp::List hw3_read_sst_multi(Rcpp::CharacterVector files, std::string var_name, Rcpp::Nullable<Rcpp::NumericVector> lon_range, Rcpp::Nullable<Rcpp::NumericVector> lat_range, int depth);
RcppExport SEXP _heatwave3_hw3_read_sst_multi(SEXP filesSEXP, SEXP var_nameSEXP, SEXP lon_rangeSEXP, SEXP lat_rangeSEXP, SEXP depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lon_range(lon_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lat_range(lat_rangeSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_read_sst_multi(files, var_name, lon_range, lat_range, depth));
    return rcpp_result_gen;
END_RCPP
}
// hw3_pixel_clim
Rcpp::List hw3_pixel_clim(Rcpp::NumericVector temp, Rcpp::IntegerVector time_jd, std::string clim_start, std::string clim_end, int windowHalfWidth, double pctile, bool smoothPercentile, int smoothPercentileWidth, int maxPadLength, bool detrend);
RcppExport SEXP _heatwave3_hw3_pixel_clim(SEXP tempSEXP, SEXP time_jdSEXP, SEXP clim_startSEXP, SEXP clim_endSEXP, SEXP windowHalfWidthSEXP, SEXP pctileSEXP, SEXP smoothPercentileSEXP, SEXP smoothPercentileWidthSEXP, SEXP maxPadLengthSEXP, SEXP detrendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type time_jd(time_jdSEXP);
    Rcpp::traits::input_parameter< std::string >::type clim_start(clim_startSEXP);
    Rcpp::traits::input_parameter< std::string >::type clim_end(clim_endSEXP);
    Rcpp::traits::input_parameter< int >::type windowHalfWidth(windowHalfWidthSEXP);
    Rcpp::traits::input_parameter< double >::type pctile(pctileSEXP);
    Rcpp::traits::input_parameter< bool >::type smoothPercentile(smoothPercentileSEXP);
    Rcpp::traits::input_parameter< int >::type smoothPercentileWidth(smoothPercentileWidthSEXP);
    Rcpp::traits::input_parameter< int >::type maxPadLength(maxPadLengthSEXP);
    Rcpp::traits::input_parameter< bool >::type detrend(detrendSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_pixel_clim(temp, time_jd, clim_start, clim_end, windowHalfWidth, pctile, smoothPercentile, smoothPercentileWidth, maxPadLength, detrend));
    return rcpp_result_gen;
END_RCPP
}
// hw3_compute_clim
void hw3_compute_clim(std::string file_in, std::string file_out, std::string var_name, Rcpp::CharacterVector climatologyPeriod, Rcpp::Nullable<Rcpp::NumericVector> lon_range, Rcpp::Nullable<Rcpp::NumericVector> lat_range, Rcpp::Nullable<Rcpp::CharacterVector> time_range, int depth, int maxPadLength, int windowHalfWidth, double pctile, bool smoothPercentile, int smoothPercentileWidth, bool compute_var, int roundClm, int n_threads, bool detrend);
RcppExport SEXP _heatwave3_hw3_compute_clim(SEXP file_inSEXP, SEXP file_outSEXP, SEXP var_nameSEXP, SEXP climatologyPeriodSEXP, SEXP lon_rangeSEXP, SEXP lat_rangeSEXP, SEXP time_rangeSEXP, SEXP depthSEXP, SEXP maxPadLengthSEXP, SEXP windowHalfWidthSEXP, SEXP pctileSEXP, SEXP smoothPercentileSEXP, SEXP smoothPercentileWidthSEXP, SEXP compute_varSEXP, SEXP roundClmSEXP, SEXP n_threadsSEXP, SEXP detrendSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_in(file_inSEXP);
    Rcpp::traits::input_parameter< std::string >::type file_out(file_outSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type climatologyPeriod(climatologyPeriodSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lon_range(lon_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lat_range(lat_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type time_range(time_rangeSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type maxPadLength(maxPadLengthSEXP);
    Rcpp::traits::input_parameter< int >::type windowHalfWidth(windowHalfWidthSEXP);
    Rcpp::traits::input_parameter< double >::type pctile(pctileSEXP);
    Rcpp::traits::input_parameter< bool >::type smoothPercentile(smoothPercentileSEXP);
    Rcpp::traits::input_parameter< int >::type smoothPercentileWidth(smoothPercentileWidthSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_var(compute_varSEXP);
    Rcpp::traits::input_parameter< int >::type roundClm(roundClmSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type detrend(detrendSEXP);
    hw3_compute_clim(file_in, file_out, var_name, climatologyPeriod, lon_range, lat_range, time_range, depth, maxPadLength, windowHalfWidth, pctile, smoothPercentile, smoothPercentileWidth, compute_var, roundClm, n_threads, detrend);
    return R_NilValue;
END_RCPP
}
// hw3_compute_clim_multi
void hw3_compute_clim_multi(Rcpp::CharacterVector files, std::string file_out, std::string var_name, Rcpp::CharacterVector climatologyPeriod, Rcpp::Nullable<Rcpp::NumericVector> lon_range, Rcpp::Nullable<Rcpp::NumericVector> lat_range, int depth, int maxPadLength, int windowHalfWidth, double pctile, bool smoothPercentile, int smoothPercentileWidth, bool compute_var, int roundClm, int n_threads, bool detrend);
RcppExport SEXP _heatwave3_hw3_compute_clim_multi(SEXP filesSEXP, SEXP file_outSEXP, SEXP var_nameSEXP, SEXP climatologyPeriodSEXP, SEXP lon_rangeSEXP, SEXP lat_rangeSEXP, SEXP depthSEXP, SEXP maxPadLengthSEXP, SEXP windowHalfWidthSEXP, SEXP pctileSEXP, SEXP smoothPercentileSEXP, SEXP smoothPercentileWidthSEXP, SEXP compute_varSEXP, SEXP roundClmSEXP, SEXP n_threadsSEXP, SEXP detrendSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< std::string >::type file_out(file_outSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type climatologyPeriod(climatologyPeriodSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lon_range(lon_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lat_range(lat_rangeSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type maxPadLength(maxPadLengthSEXP);
    Rcpp::traits::input_parameter< int >::type windowHalfWidth(windowHalfWidthSEXP);
    Rcpp::traits::input_parameter< double >::type pctile(pctileSEXP);
    Rcpp::traits::input_parameter< bool >::type smoothPercentile(smoothPercentileSEXP);
    Rcpp::traits::input_parameter< int >::type smoothPercentileWidth(smoothPercentileWidthSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_var(compute_varSEXP);
    Rcpp::traits::input_parameter< int >::type roundClm(roundClmSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type detrend(detrendSEXP);
    hw3_compute_clim_multi(files, file_out, var_name, climatologyPeriod, lon_range, lat_range, depth, maxPadLength, windowHalfWidth, pctile, smoothPercentile, smoothPercentileWidth, compute_var, roundClm, n_threads, detrend);
    return R_NilValue;
END_RCPP
}
// hw3_write_const_clim
void hw3_write_const_clim(std::string file_in, std::string clim_file, std::string var_name, double threshold, Rcpp::Nullable<Rcpp::NumericVector> lon_range, Rcpp::Nullable<Rcpp::NumericVector> lat_range, Rcpp::Nullable<Rcpp::CharacterVector> time_range, int depth);
RcppExport SEXP _heatwave3_hw3_write_const_clim(SEXP file_inSEXP, SEXP clim_fileSEXP, SEXP var_nameSEXP, SEXP thresholdSEXP, SEXP lon_rangeSEXP, SEXP lat_rangeSEXP, SEXP time_rangeSEXP, SEXP depthSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_in(file_inSEXP);
    Rcpp::traits::input_parameter< std::string >::type clim_file(clim_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lon_range(lon_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lat_range(lat_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type time_range(time_rangeSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    hw3_write_const_clim(file_in, clim_file, var_name, threshold, lon_range, lat_range, time_range, depth);
    return R_NilValue;
END_RCPP
}
// hw3_jd_to_doy
int hw3_jd_to_doy(int jd);
RcppExport SEXP _heatwave3_hw3_jd_to_doy(SEXP jdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type jd(jdSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_jd_to_doy(jd));
    return rcpp_result_gen;
END_RCPP
}
// hw3_read_clim_nc
Rcpp::List hw3_read_clim_nc(std::string clim_file);
RcppExport SEXP _heatwave3_hw3_read_clim_nc(SEXP clim_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type clim_file(clim_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(hw3_read_clim_nc(clim_file));
    return rcpp_result_gen;
END_RCPP
}
// hw3_detect_events
void hw3_detect_events(std::string file_in, std::string clim_file, std::string file_out, std::string var_name, int minDuration, int minDuration2, bool joinAcrossGaps, int maxGap, int maxGap2, bool coldSpells, int roundRes, int n_threads);
RcppExport SEXP _heatwave3_hw3_detect_events(SEXP file_inSEXP, SEXP clim_fileSEXP, SEXP file_outSEXP, SEXP var_nameSEXP, SEXP minDurationSEXP, SEXP minDuration2SEXP, SEXP joinAcrossGapsSEXP, SEXP maxGapSEXP, SEXP maxGap2SEXP, SEXP coldSpellsSEXP, SEXP roundResSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_in(file_inSEXP);
    Rcpp::traits::input_parameter< std::string >::type clim_file(clim_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type file_out(file_outSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< int >::type minDuration(minDurationSEXP);
    Rcpp::traits::input_parameter< int >::type minDuration2(minDuration2SEXP);
    Rcpp::traits::input_parameter< bool >::type joinAcrossGaps(joinAcrossGapsSEXP);
    Rcpp::traits::input_parameter< int >::type maxGap(maxGapSEXP);
    Rcpp::traits::input_parameter< int >::type maxGap2(maxGap2SEXP);
    Rcpp::traits::input_parameter< bool >::type coldSpells(coldSpellsSEXP);
    Rcpp::traits::input_parameter< int >::type roundRes(roundResSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    hw3_detect_events(file_in, clim_file, file_out, var_name, minDuration, minDuration2, joinAcrossGaps, maxGap, maxGap2, coldSpells, roundRes, n_threads);
    return R_NilValue;
END_RCPP
}
// hw3_detect_events_multi
void hw3_detect_events_multi(Rcpp::CharacterVector files, std::string clim_file, std::string file_out, std::string var_name, int minDuration, int minDuration2, bool joinAcrossGaps, int maxGap, int maxGap2, bool coldSpells, int roundRes, int n_threads);
RcppExport SEXP _heatwave3_hw3_detect_events_multi(SEXP filesSEXP, SEXP clim_fileSEXP, SEXP file_outSEXP, SEXP var_nameSEXP, SEXP minDurationSEXP, SEXP minDuration2SEXP, SEXP joinAcrossGapsSEXP, SEXP maxGapSEXP, SEXP maxGap2SEXP, SEXP coldSpellsSEXP, SEXP roundResSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< std::string >::type clim_file(clim_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type file_out(file_outSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< int >::type minDuration(minDurationSEXP);
    Rcpp::traits::input_parameter< int >::type minDuration2(minDuration2SEXP);
    Rcpp::traits::input_parameter< bool >::type joinAcrossGaps(joinAcrossGapsSEXP);
    Rcpp::traits::input_parameter< int >::type maxGap(maxGapSEXP);
    Rcpp::traits::input_parameter< int >::type maxGap2(maxGap2SEXP);
    Rcpp::traits::input_parameter< bool >::type coldSpells(coldSpellsSEXP);
    Rcpp::traits::input_parameter< int >::type roundRes(roundResSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    hw3_detect_events_multi(files, clim_file, file_out, var_name, minDuration, minDuration2, joinAcrossGaps, maxGap, maxGap2, coldSpells, roundRes, n_threads);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_heatwave3_label_components_3d_cpp", (DL_FUNC) &_heatwave3_label_components_3d_cpp, 5},
    {"_heatwave3_blob_daily_summary_cpp", (DL_FUNC) &_heatwave3_blob_daily_summary_cpp, 9},
    {"_heatwave3_hw3_version", (DL_FUNC) &_heatwave3_hw3_version, 0},
    {"_heatwave3_hw3_read_sst", (DL_FUNC) &_heatwave3_hw3_read_sst, 6},
    {"_heatwave3_hw3_read_sst_multi", (DL_FUNC) &_heatwave3_hw3_read_sst_multi, 5},
    {"_heatwave3_hw3_pixel_clim", (DL_FUNC) &_heatwave3_hw3_pixel_clim, 10},
    {"_heatwave3_hw3_compute_clim", (DL_FUNC) &_heatwave3_hw3_compute_clim, 17},
    {"_heatwave3_hw3_compute_clim_multi", (DL_FUNC) &_heatwave3_hw3_compute_clim_multi, 16},
    {"_heatwave3_hw3_write_const_clim", (DL_FUNC) &_heatwave3_hw3_write_const_clim, 8},
    {"_heatwave3_hw3_jd_to_doy", (DL_FUNC) &_heatwave3_hw3_jd_to_doy, 1},
    {"_heatwave3_hw3_read_clim_nc", (DL_FUNC) &_heatwave3_hw3_read_clim_nc, 1},
    {"_heatwave3_hw3_detect_events", (DL_FUNC) &_heatwave3_hw3_detect_events, 12},
    {"_heatwave3_hw3_detect_events_multi", (DL_FUNC) &_heatwave3_hw3_detect_events_multi, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_heatwave3(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
